[theme]
# Deep space blue primary color, you can adjust the shade as needed
primaryColor = "#1B1F36"

backgroundColor = "#1A1A1A"

# Slightly lighter grey for the sidebar and interactive widgets to distinguish from the main content area
secondaryBackgroundColor = "#2A2A2A"

# White text color for readability on the dark grey background
textColor = "#FFFFFF"

# Font style
font = "sans serif"